use std::{collections::BTreeSet, fmt};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Migration {
    pub version: u32,
    pub name: &'static str,
    pub statements: &'static [&'static str],
    pub checksum: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MigrationValidationError {
    EmptySet,
    InvalidName { version: u32, name: String },
    EmptyStatement { version: u32 },
    NonIncreasingVersion { previous: u32, current: u32 },
    DuplicateVersion(u32),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MigrationRunError {
    Validation(MigrationValidationError),
    Statement {
        version: u32,
        name: &'static str,
        statement_index: usize,
        source: String,
    },
    MarkApplied {
        version: u32,
        name: &'static str,
        source: String,
    },
}

pub trait MigrationExecutor {
    fn execute_statement(&mut self, statement: &str) -> Result<(), String>;
    fn mark_applied(&mut self, migration: &Migration) -> Result<(), String>;
}

pub fn all() -> &'static [Migration] {
    MIGRATIONS
}

pub fn validate(migrations: &[Migration]) -> Result<(), MigrationValidationError> {
    if migrations.is_empty() {
        return Err(MigrationValidationError::EmptySet);
    }

    let mut previous = None;
    let mut seen = BTreeSet::new();
    for migration in migrations {
        if let Some(previous) = previous
            && migration.version <= previous
        {
            return Err(MigrationValidationError::NonIncreasingVersion {
                previous,
                current: migration.version,
            });
        }
        previous = Some(migration.version);

        if !seen.insert(migration.version) {
            return Err(MigrationValidationError::DuplicateVersion(
                migration.version,
            ));
        }

        if !valid_name(migration.name) {
            return Err(MigrationValidationError::InvalidName {
                version: migration.version,
                name: migration.name.to_owned(),
            });
        }

        for statement in migration.statements {
            if statement.trim().is_empty() {
                return Err(MigrationValidationError::EmptyStatement {
                    version: migration.version,
                });
            }
        }
    }

    Ok(())
}

pub fn render_all() -> Result<String, MigrationValidationError> {
    validate(MIGRATIONS)?;

    let mut output = String::new();
    output.push_str("-- Mythenheim SurrealDB schema migrations.\n");
    output.push_str("-- Generated by mythenheim --print-migrations.\n\n");
    for migration in MIGRATIONS {
        output.push_str(&format!(
            "-- migration {:04}: {}\n",
            migration.version, migration.name
        ));
        for statement in migration.statements {
            output.push_str(statement.trim());
            output.push_str("\n\n");
        }
        output.push_str(&mark_applied_statement(migration));
        output.push_str("\n\n");
    }

    Ok(output)
}

pub fn run<E: MigrationExecutor>(
    migrations: &[Migration],
    executor: &mut E,
) -> Result<(), MigrationRunError> {
    validate(migrations).map_err(MigrationRunError::Validation)?;

    for migration in migrations {
        for (index, statement) in migration.statements.iter().enumerate() {
            executor.execute_statement(statement).map_err(|source| {
                MigrationRunError::Statement {
                    version: migration.version,
                    name: migration.name,
                    statement_index: index,
                    source,
                }
            })?;
        }
        executor
            .mark_applied(migration)
            .map_err(|source| MigrationRunError::MarkApplied {
                version: migration.version,
                name: migration.name,
                source,
            })?;
    }

    Ok(())
}

pub fn mark_applied_statement(migration: &Migration) -> String {
    format!(
        "UPSERT mythenheim_migration:{} CONTENT {{ version: {}, name: {:?}, checksum: {:?}, applied_at: time::now() }};",
        migration.version, migration.version, migration.name, migration.checksum
    )
}

impl fmt::Display for MigrationValidationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptySet => formatter.write_str("migration set is empty"),
            Self::InvalidName { version, name } => {
                write!(formatter, "migration {version} has invalid name {name:?}")
            }
            Self::EmptyStatement { version } => {
                write!(formatter, "migration {version} has an empty statement")
            }
            Self::NonIncreasingVersion { previous, current } => write!(
                formatter,
                "migration version {current} must be greater than previous version {previous}"
            ),
            Self::DuplicateVersion(version) => {
                write!(
                    formatter,
                    "migration version {version} appears more than once"
                )
            }
        }
    }
}

impl std::error::Error for MigrationValidationError {}

impl fmt::Display for MigrationRunError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Validation(err) => write!(formatter, "migration validation failed: {err}"),
            Self::Statement {
                version,
                name,
                statement_index,
                source,
            } => write!(
                formatter,
                "migration {version} ({name}) statement {statement_index} failed: {source}"
            ),
            Self::MarkApplied {
                version,
                name,
                source,
            } => write!(
                formatter,
                "migration {version} ({name}) could not be marked applied: {source}"
            ),
        }
    }
}

impl std::error::Error for MigrationRunError {}

fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_' || byte == b'-'
        })
}

const MIGRATIONS: &[Migration] = &[
    Migration {
        version: 1,
        name: "migration_bookkeeping",
        checksum: "0000000000000000000000000000000000000000000000000000000000000001",
        statements: &[
            "DEFINE TABLE IF NOT EXISTS mythenheim_migration SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS version ON TABLE mythenheim_migration TYPE int ASSERT $value > 0;",
            "DEFINE FIELD IF NOT EXISTS name ON TABLE mythenheim_migration TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS checksum ON TABLE mythenheim_migration TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS applied_at ON TABLE mythenheim_migration TYPE datetime DEFAULT time::now();",
            "DEFINE INDEX IF NOT EXISTS mythenheim_migration_version_unique ON TABLE mythenheim_migration FIELDS version UNIQUE;",
        ],
    },
    Migration {
        version: 2,
        name: "identity_and_roles",
        checksum: "0000000000000000000000000000000000000000000000000000000000000002",
        statements: &[
            "DEFINE TABLE IF NOT EXISTS user SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS username ON TABLE user TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS username_normalized ON TABLE user TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS email_hash ON TABLE user TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS password_hash ON TABLE user TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS trust_level ON TABLE user TYPE int DEFAULT 0 ASSERT $value >= 0 AND $value <= 4;",
            "DEFINE FIELD IF NOT EXISTS status ON TABLE user TYPE string DEFAULT 'active' ASSERT $value INSIDE ['active', 'muted', 'banned', 'shadowbanned', 'deleted'];",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE user TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS updated_at ON TABLE user TYPE option<datetime>;",
            "DEFINE INDEX IF NOT EXISTS user_username_unique ON TABLE user FIELDS username_normalized UNIQUE;",
            "DEFINE INDEX IF NOT EXISTS user_email_hash_unique ON TABLE user FIELDS email_hash UNIQUE;",
            "DEFINE TABLE IF NOT EXISTS role SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS name ON TABLE role TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS description ON TABLE role TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS capabilities ON TABLE role TYPE array<string> DEFAULT [];",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE role TYPE datetime DEFAULT time::now();",
            "DEFINE INDEX IF NOT EXISTS role_name_unique ON TABLE role FIELDS name UNIQUE;",
            "DEFINE TABLE IF NOT EXISTS session SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS user ON TABLE session TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS token_hash ON TABLE session TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE session TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS expires_at ON TABLE session TYPE datetime;",
            "DEFINE FIELD IF NOT EXISTS revoked_at ON TABLE session TYPE option<datetime>;",
            "DEFINE FIELD IF NOT EXISTS user_agent_hash ON TABLE session TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS ip_hash ON TABLE session TYPE option<string>;",
            "DEFINE INDEX IF NOT EXISTS session_token_hash_unique ON TABLE session FIELDS token_hash UNIQUE;",
        ],
    },
    Migration {
        version: 3,
        name: "forum_core",
        checksum: "0000000000000000000000000000000000000000000000000000000000000003",
        statements: &[
            "DEFINE TABLE IF NOT EXISTS category SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS name ON TABLE category TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS slug ON TABLE category TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS description ON TABLE category TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS parent ON TABLE category TYPE option<record<category>>;",
            "DEFINE FIELD IF NOT EXISTS display_order ON TABLE category TYPE int DEFAULT 0;",
            "DEFINE FIELD IF NOT EXISTS is_locked ON TABLE category TYPE bool DEFAULT false;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE category TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS updated_at ON TABLE category TYPE option<datetime>;",
            "DEFINE INDEX IF NOT EXISTS category_slug_unique ON TABLE category FIELDS slug UNIQUE;",
            "DEFINE TABLE IF NOT EXISTS topic SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS category ON TABLE topic TYPE record<category>;",
            "DEFINE FIELD IF NOT EXISTS author ON TABLE topic TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS title ON TABLE topic TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS slug ON TABLE topic TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS kind ON TABLE topic TYPE string DEFAULT 'discussion' ASSERT $value INSIDE ['discussion', 'question', 'suggestion', 'article', 'poll'];",
            "DEFINE FIELD IF NOT EXISTS view_count ON TABLE topic TYPE int DEFAULT 0 ASSERT $value >= 0;",
            "DEFINE FIELD IF NOT EXISTS reply_count ON TABLE topic TYPE int DEFAULT 0 ASSERT $value >= 0;",
            "DEFINE FIELD IF NOT EXISTS is_pinned ON TABLE topic TYPE bool DEFAULT false;",
            "DEFINE FIELD IF NOT EXISTS is_locked ON TABLE topic TYPE bool DEFAULT false;",
            "DEFINE FIELD IF NOT EXISTS deleted_at ON TABLE topic TYPE option<datetime>;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE topic TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS updated_at ON TABLE topic TYPE option<datetime>;",
            "DEFINE INDEX IF NOT EXISTS topic_category_slug_unique ON TABLE topic FIELDS category, slug UNIQUE;",
            "DEFINE TABLE IF NOT EXISTS post SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS topic ON TABLE post TYPE record<topic>;",
            "DEFINE FIELD IF NOT EXISTS author ON TABLE post TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS content_raw ON TABLE post TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS content_html ON TABLE post TYPE string;",
            "DEFINE FIELD IF NOT EXISTS revision ON TABLE post TYPE int DEFAULT 1 ASSERT $value > 0;",
            "DEFINE FIELD IF NOT EXISTS moderation_state ON TABLE post TYPE string DEFAULT 'visible' ASSERT $value INSIDE ['visible', 'pending', 'hidden', 'deleted'];",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE post TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS updated_at ON TABLE post TYPE option<datetime>;",
            "DEFINE FIELD IF NOT EXISTS deleted_at ON TABLE post TYPE option<datetime>;",
        ],
    },
    Migration {
        version: 4,
        name: "moderation_and_audit",
        checksum: "0000000000000000000000000000000000000000000000000000000000000004",
        statements: &[
            "DEFINE TABLE IF NOT EXISTS audit_log SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS actor ON TABLE audit_log TYPE option<record<user>>;",
            "DEFINE FIELD IF NOT EXISTS action ON TABLE audit_log TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS target ON TABLE audit_log TYPE option<string>;",
            "DEFINE FIELD IF NOT EXISTS previous_state ON TABLE audit_log TYPE option<object>;",
            "DEFINE FIELD IF NOT EXISTS metadata ON TABLE audit_log TYPE object DEFAULT {};",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE audit_log TYPE datetime DEFAULT time::now();",
            "DEFINE TABLE IF NOT EXISTS warning SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS user ON TABLE warning TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS actor ON TABLE warning TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS reason ON TABLE warning TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS points ON TABLE warning TYPE int ASSERT $value > 0;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE warning TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS expires_at ON TABLE warning TYPE option<datetime>;",
            "DEFINE TABLE IF NOT EXISTS report SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS reporter ON TABLE report TYPE record<user>;",
            "DEFINE FIELD IF NOT EXISTS target ON TABLE report TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS reason ON TABLE report TYPE string ASSERT $value != '';",
            "DEFINE FIELD IF NOT EXISTS state ON TABLE report TYPE string DEFAULT 'open' ASSERT $value INSIDE ['open', 'accepted', 'rejected'];",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE report TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS resolved_at ON TABLE report TYPE option<datetime>;",
        ],
    },
    Migration {
        version: 5,
        name: "forum_graph_edges",
        checksum: "0000000000000000000000000000000000000000000000000000000000000005",
        statements: &[
            "DEFINE TABLE IF NOT EXISTS has_role TYPE RELATION IN user OUT role SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS granted_at ON TABLE has_role TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS granted_by ON TABLE has_role TYPE option<record<user>>;",
            "DEFINE TABLE IF NOT EXISTS moderates TYPE RELATION IN user OUT category SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS granted_at ON TABLE moderates TYPE datetime DEFAULT time::now();",
            "DEFINE FIELD IF NOT EXISTS granted_by ON TABLE moderates TYPE option<record<user>>;",
            "DEFINE TABLE IF NOT EXISTS posted TYPE RELATION IN user OUT post SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE posted TYPE datetime DEFAULT time::now();",
            "DEFINE TABLE IF NOT EXISTS belongs_to TYPE RELATION IN post|topic OUT topic|category SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE belongs_to TYPE datetime DEFAULT time::now();",
            "DEFINE TABLE IF NOT EXISTS read_marker TYPE RELATION IN user OUT topic|post SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS read_at ON TABLE read_marker TYPE datetime DEFAULT time::now();",
            "DEFINE TABLE IF NOT EXISTS watches TYPE RELATION IN user OUT category|topic SCHEMAFULL;",
            "DEFINE FIELD IF NOT EXISTS created_at ON TABLE watches TYPE datetime DEFAULT time::now();",
        ],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Default)]
    struct RecordingExecutor {
        statements: Vec<String>,
        marked: Vec<u32>,
        fail_statement: Option<usize>,
    }

    impl MigrationExecutor for RecordingExecutor {
        fn execute_statement(&mut self, statement: &str) -> Result<(), String> {
            let next = self.statements.len();
            if self.fail_statement == Some(next) {
                return Err("forced statement failure".to_owned());
            }
            self.statements.push(statement.to_owned());
            Ok(())
        }

        fn mark_applied(&mut self, migration: &Migration) -> Result<(), String> {
            self.marked.push(migration.version);
            Ok(())
        }
    }

    #[test]
    fn migrations_are_valid() {
        validate(all()).unwrap();
    }

    #[test]
    fn render_includes_core_tables_and_markers() {
        let rendered = render_all().unwrap();

        assert!(rendered.contains("DEFINE TABLE IF NOT EXISTS user SCHEMAFULL;"));
        assert!(rendered.contains("DEFINE TABLE IF NOT EXISTS audit_log SCHEMAFULL;"));
        assert!(rendered.contains("DEFINE TABLE IF NOT EXISTS has_role TYPE RELATION"));
        assert!(rendered.contains("UPSERT mythenheim_migration:5"));
    }

    #[test]
    fn runner_marks_migration_after_statements() {
        let mut executor = RecordingExecutor::default();

        run(&all()[..1], &mut executor).unwrap();

        assert_eq!(executor.marked, vec![1]);
        assert_eq!(executor.statements.len(), all()[0].statements.len());
    }

    #[test]
    fn runner_does_not_mark_failed_migration() {
        let mut executor = RecordingExecutor {
            fail_statement: Some(1),
            ..RecordingExecutor::default()
        };

        let err = run(&all()[..1], &mut executor).unwrap_err();

        assert!(err.to_string().contains("forced statement failure"));
        assert!(executor.marked.is_empty());
    }

    #[test]
    fn validation_rejects_non_increasing_versions() {
        let migrations = [
            Migration {
                version: 2,
                name: "second",
                statements: &["SELECT 1;"],
                checksum: "2",
            },
            Migration {
                version: 1,
                name: "first",
                statements: &["SELECT 1;"],
                checksum: "1",
            },
        ];

        assert!(matches!(
            validate(&migrations),
            Err(MigrationValidationError::NonIncreasingVersion { .. })
        ));
    }
}
